#!/usr/bin/env php
<?php

/**
 * CodeRage shell
 *
 * File:        CodeRage/Sys/crush
 * Date:        Mon Jan 28 10:40:18 MST 2008
 * Notice:      This document contains confidential information
 *              and trade secrets
 *
 * @copyright   2015 CounselNow, LLC
 * @author      Jonathan Turkanis
 * @license     All rights reserved
 */

$file = __DIR__ . '/../../../../autoload.php';
if (file_exists($file)) {
    require $file;
} else {
    throw new RuntimeException("Failed locating autoload.php");
}

CodeRage\Util\ErrorHandler::register();
exit((new CodeRage\Sys\CommandLine)->execute() ? 0 : 1);
