#!/bin/env php
<?php

$file = __DIR__ . '/../../../../autoload.php';
if (file_exists($file)) {
    require $file;
} else {
    throw new RuntimeException("Failed locating autoload.php");
}

if (sizeof($argv) != 2) {
    $error = fopen('php://stderr', 'w');
    fwrite($error, "Usage: decode-id OBJECT_ID\n");
    exit(1);
}
$id = $argv[1];
echo CodeRage\Access\ResourceId::decode($id);
